### ISSUE TITLE
Without Images

### ISSUE THREAD

**Issue by nguyenj** [pfarmer/jquery-countdown#11]
Is there a possibility to use this plugin without images? I'd just like to use regular text.

**Comment by pfarmer** [comment]
Hi,

Thanks for you interest in this plugin, unfortunately a lot of the code in this plugin is based around switching the images, I'll look into do a text version which can be skinned by css, however in the mean time, can I suggest:

http://keith-wood.name/countdown.html

Peter

**Comment by nguyenj** [comment]
hi, peter.
i appreciate the link.
