### ISSUE TITLE
Add methods to start/stop/reset countdown

### ISSUE THREAD

**Issue by mrbrazzi** [pfarmer/jquery-countdown#12]
Hi, great work, could you include methods to start/stop/reset countdown like this example http://www.littlewebthings.com/projects/countdown/example.php?e=start_stop ?

Best regards...

**Comment by pfarmer** [comment]
Could you give some example use cases?

Thanks,

**Comment by mrbrazzi** [comment]
I would like have 2 methods countdownSart and countdownStop, and if I have two buttons (START & STOP) when I click on STOP button then countdown stop and when I click START button it resume or start from begining. Something like this:
[html]
      < input id="start" type="button" value=" START ">&nbsp;|&nbsp;< input id="stop" type="button" value=" STOP " >
[/html]

[script]
        $('#start').click(function(){
          $('#my_countdown').countdownStart({
              startTime: new Date(),
              stepTime: 1,
              digitImages: 6,
              digitWidth: 53,
              digitHeight: 77,
              image: "images/digits.png"
            });
        });

```
    $('#stop').click(function(){
      $('#my_countdown').countdownStop();
    });        
```

[/script]

Thanks...
Best regards

**Comment by pfarmer** [comment]
Hi,

I understand what you want to do, but I'm trying to understand in what situation you would use stop/start/reset methods.

Peter

**Comment by pfarmer** [comment]
Code has been merged which includes this functionality.
