### ISSUE TITLE
Calculate date wrong?

### ISSUE THREAD

**Issue by streetrobban** [pfarmer/jquery-countdown#15]
Hello,

I don't know if I missunderstand the Date Object?

If I set the date like this:

```
var _date = new Date();
_date.setMonth(10);
_date.setDate(28);
_date.setHours(18);
_date.setMinutes(00);
_date.setSeconds(00);
$('#counter11').countdown({
    startTime: _date,
    stepTime: 1,
    digitImages: 6,
    digitWidth: 53,
    digitHeight: 77,
    image: "img/digits.png"
});
```

It's in a week (today it's 2011-10-21 11:44). So I would expect the timer to start at 06:06:16:00 right? Right now it says 38:07:14:00. I don't get it?

**Comment by pfarmer** [comment]
Hi,

Please see:

http://www.w3schools.com/jsref/jsref_setmonth.asp

October is month "9" in the Date object not "10".

Thanks,

Peter

**Comment by streetrobban** [comment]
Ah, I see! Thanks alot :)

**Comment by pfarmer** [comment]
Your welcome, don't forget to add your site to the wiki.

Peter
