### ISSUE TITLE
Message after countdown expires

### ISSUE THREAD

**Issue by Legin76** [pfarmer/jquery-countdown#21]
This may be more down to my lack of jquery knowledge. 

I'm trying to do a countdown to new year that displays "Happy New Year" after midnight. It works if you have the coundown on your screen at the time, but the problem I'm getting is that if you load the page after the countdown has finished, it starts counting down again. I want it just to display the  "Happy New Year" message on page loads after the coundown has finished.

The code I've used is blow.

```
  $(function(){
    var _date = new Date();
    _date.setYear(2012);
    _date.setMonth(0);
    _date.setDate(0);
    _date.setHours(0);
    _date.setMinutes(0);
    _date.setSeconds(0);
    $('#counter').countdown({
        startTime: _date,
        digitWidth: 53,
        digitHeight: 77,
        image: 'img/digits_inverted.png',
        timerEnd: function(){ $("#counter").html("<div style='font-size: 4em;'>Happy New Year!</div>"); },
    });
```

**Comment by pfarmer** [comment]
I think what you are trying to achive is outside of the scope of this project. Perhap you should wrap your above countdown function in another function which does a test on the date, if it is after the new year, display you message, if it is before, start the countdown.
