### ISSUE TITLE
Image flip animation

### ISSUE THREAD

**Issue by Legin76** [pfarmer/jquery-countdown#22]
When the coundown updates it only does the animated flip on one figure at a time rather than all of the ones that are changing...

For example.. If the there are 20 seconds on the countdown when it changes to 19 only the 1 will animate. The 0 to 9 will just be an image swap. On a change from 20:00 to 19:59 then only the change from 2 to 1 will be animated.

**Comment by pfarmer** [comment]
Yes, 0 to 9 is an image swap, not a flip.

**Comment by Legin76** [comment]
Is it possible to make it do it as a flip? There images are in the grapic for it?
