### ISSUE TITLE
digit 9 jumps 1 pixel up.

### ISSUE THREAD

**Issue by pfarmer** [pfarmer/jquery-countdown#7]

**Comment by martijnonline** [comment]
I fixed this problem. Here is a new digits.png:
http://cl.ly/B2t6

**Comment by pfarmer** [comment]
Super, thanks, would it be possible for you to send me a pull request so you get proper credit in the source history? If I'll credit you in the log message.

**Comment by ruant** [comment]
This is fixed right? Close it?

**Comment by pfarmer** [comment]
Fixed by 050e913ce9178849cd79ec3010a6d81ef73f03ce.
